# Ejercicio 1

Pedir al usuario la longitud de una lista. Que introduzca tantos número enteros como haya indicado. Imprimir la lista.

In [2]:
l = int(input("Introduce la longitud deseada para una lista: "))
list = []

for c in range(l):
    n = int(input("Introduce un número: "))
    list.append(n)
    
print(list)

[5, 4]


# Ejercicio 2

Crear una matriz 3x3 de números enteros y guardarla en una lista

## Mi solución

In [16]:
A = []
for i in range(3):
    fila_i = []
    for j in range(3):
        n = int(input("Introduce el elemento {}{}".format(i+1,j+1)))
        fila_i.extend([n])       
    A.extend([fila_i])
print(A)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


## Solución del curso

In [17]:
A = []
for i in range(3):
    A.append([])
    for j in range(3):
        n = int(input("Introduce el elemento ({},{}): ".format(i+1,j+1)))  
        A[i].append(n)
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


# Ejercicio 3

Sumar dos matrices con listas. Ambas matrices (incluida la dimensión) son proporcionadas por el usuario.

In [36]:
print("Se te piden dos matrices para obtener la suma")

n = int(input("\nIntroduce el número de filas de las matrices"))
m = int(input("Introduce el número de columnas de las matrices"))

print("\nIntroduce la primera matriz A: ")
A = []
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}): ".format(i+1,j+1))))
print("La matriz A = {}".format(A))

print("\nIntroduce la segunda matriz B: ")
B = []
for i in range(n):
    B.append([])
    for j in range(m):
        B[i].append(float(input("Introduce el elemento ({},{}): ".format(i+1,j+1))))
print("La matriz B = {}".format(B))

C = []
for i in range(n):
    C.append([])
    for j in range(m):
        sum = A[i][j] + B[i][j]
        C[i].append(sum)


print("\nLa matriz suma C = A + B = {}".format(C))

print("\n*****Impreso más bonito ***** \n***** La matriz suma es ***** ")

for i in range(m):
    for j in range(n):
        print(C[i][j], end = "  " if C[i][j] else " ")
    print("")

Se te piden dos matrices para obtener la suma

Introduce la primera matriz A: 
La matriz A = [[1.0, 2.0], [3.0, 4.0]]

Introduce la primera matriz B: 
La matriz B = [[5.0, 6.0], [7.0, 8.0]]

La matriz suma C = A + B = [[6.0, 8.0], [10.0, 12.0]]

*****Impreso más bonito ***** 
***** La matriz suma es ***** 
6.0  8.0  
10.0  12.0  


# Ejercicio 4

Multiplicar dos matrices con listas. Ambas matrices (incluida la dimensión) son proporcionadas por el usuario.

In [37]:
print("Se te piden dos matrices para obtener el producto")

n = int(input("\nIntroduce el número de filas de la matriz A"))
m = int(input("Introduce el número de columnas de la matriz A"))
p = int(input("Introduce el número de filas de la matriz B"))

print("\nIntroduce la primera matriz A: ")
A = []
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}): ".format(i+1,j+1))))
print("La matriz A = {}".format(A))

print("\nIntroduce la segunda matriz B: ")
B = []
for i in range(m):
    B.append([])
    for j in range(p):
        B[i].append(float(input("Introduce el elemento ({},{}): ".format(i+1,j+1))))
print("La matriz B = {}".format(B))

C = []
for i in range(n):
    C.append([])
    for j in range(p):
        sum = 0
        for k in range(m):
            prod = A[i][k] * B[k][j]
            sum = sum + prod
        C[i].append(sum)

print("\nLa matriz producto C = A * B = {}".format(C))

print("\n*****Impreso más bonito ***** \n***** La matriz producto es ***** ")

for i in range(m):
    for j in range(n):
        print(C[i][j], end = "  " if C[i][j] else " ")
    print("")

Se te piden dos matrices para obtener el producto

Introduce la primera matriz A: 
La matriz A = [[1.0, 2.0], [3.0, 4.0]]

Introduce la segunda matriz B: 
La matriz B = [[5.0, 6.0, 1.0], [2.0, 4.0, 5.0]]

La matriz suma C = A + B = [[9.0, 14.0, 11.0], [23.0, 34.0, 23.0]]

*****Impreso más bonito ***** 
***** La matriz suma es ***** 
9.0  14.0  
23.0  34.0  


# Ejercicio 4

Que el usuario nos de una matriz. Utilizar numpy.

## Mi solución

In [40]:
import numpy as np
n = int(input("Introduce el número de filas: "))
m = int(input("Introduce el número de columnas: "))

print("\nIntroduce la primera matriz A: ")
A = []
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}): ".format(i+1,j+1))))

A = np.matrix(A)
print(A)



Introduce la primera matriz A: 
[[1. 2.]
 [3. 4.]]


## Solución del curso

In [45]:
import numpy as np
n = int(input("Introduce el número de filas: "))
m = int(input("Introduce el número de columnas: "))

A = np.empty((n,m))

for i in range(n):
    for j in range(m):
        A[i,j] = float(input("Introduce el elemento ({},{}): ".format(i+1,j+1)))

print(A)

[[1. 2.]
 [3. 4.]]


# Ejercicio 5

Sumar dos matrices con numpy. Datos dados por el usuario.

In [52]:
import numpy as np
n = int(input("Introduce el número de filas: "))
m = int(input("Introduce el número de columnas: "))

print("\nIntroduce la primera matriz A: ")
A = np.empty((n,m))

for i in range(n):
    for j in range(m):
        A[i,j] = float(input("Introduce el elemento ({},{}): ".format(i+1,j+1)))

print(A)

print("\nIntroduce la primera matriz B: ")
B = np.empty((n,m))

for i in range(n):
    for j in range(m):
        B[i,j] = float(input("Introduce el elemento ({},{}): ".format(i+1,j+1)))

print(B)

print("\nLa matriz suma es \n{}: ".format(A+B))


Introduce la primera matriz A: 
[[1. 2.]
 [3. 4.]]

Introduce la primera matriz B: 
[[5. 1.]
 [2. 7.]]

La matriz suma es 
[[ 6.  3.]
 [ 5. 11.]]: 


# Ejercicio 6

Multiplicar dos matrices con numpy. Datos dados por el usuario.

In [53]:
import numpy as np
n = int(input("Introduce el número de filas de A: "))
m = int(input("Introduce el número de columnas de A: "))
p = int(input("Introduce el número de columnas de B: "))

print("\nIntroduce la primera matriz A: ")
A = np.empty((n,m))

for i in range(n):
    for j in range(m):
        A[i,j] = float(input("Introduce el elemento ({},{}): ".format(i+1,j+1)))

print(A)

print("\nIntroduce la primera matriz B: ")
B = np.empty((m,p))

for i in range(m):
    for j in range(p):
        B[i,j] = float(input("Introduce el elemento ({},{}): ".format(i+1,j+1)))

print(B)

print("\nLa matriz producto es \n{}: ".format(A.dot(B)))


Introduce la primera matriz A: 
[[ 1.  5.  8.]
 [10. 56.  4.]]

Introduce la primera matriz B: 
[[   5.  -12. -100.  -45.    4.]
 [  50.  -10.   15.   10.   45.]
 [   8.   45.   15.    4.    5.]]

La matriz suma es 
[[ 319.  298.   95.   37.  269.]
 [2882. -500. -100.  126. 2580.]]: 


# Tarea

In [131]:
# Ejercicio 1

string = input("Introduce una frase: ")

list = []

for c in string:
    list.append(c)

list.reverse()

for c in list:
    print(c, end = " ")


a l o h 

In [108]:
# Ejercicio 3

string = input("Introduce una frase: ")

list = []

for c in string:
    if c == "a" or c == "e" or c == "i" or c == "o" or c == "u" or c == " ":
        continue
    list.append(c)

print(list)

['h', 'l', 'q', 't', 'l']


In [130]:
# Ejercicio 4

string = input("Introduce una palabra: ")

list, list_reverse = [], []
for c in string:
    list.append(c)
    list_reverse.append(c)

list_reverse.reverse()
                  
for i in range(len(list)):
    if list[i] != list_reverse[i]:
        print("La palabra {} no es un palíndromo".format(string))
        break
else:
    print("La palabra {} es un palíndromo".format(string))      

La palabra holaaloh es un palíndromo


In [134]:
# Ejercicio 5

import numpy as np

print("Introduce una matriz 3x3: ")

A = np.empty((3,3))

for i in range(3):
    for j in range(3):
        A[i,j] = float(input("Introduce el elemento ({},{})".format(i+1,j+1)))

print(A)

for i in range(3):
    max = A[i,1]
    for j in range(3):
        if A[i,j] > max:
            max = A[i,j]
    print("El máximo de la fila {} es {}".format(i+1,max))
        


Introduce una matriz 3x3: 
[[ 12. 500. -12.]
 [-15. -26.  -2.]
 [ 15.  48.  50.]]
El máximo de la fila 0 es 500.0
El máximo de la fila 1 es -2.0
El máximo de la fila 2 es 50.0
